// In Next JS, For Every Folder, we have 2 main files and that files should be present
// First One is layout.tsx and Second One is page.tsx
// layout.tsx ==> This File Generally Used to define the layout for the Page
// page.tsx ==> This File Contains the Content that we have to show or display on the web page

// Importing the Metadata for the Web Page
import type { Metadata } from "next";

// Importing the Inter Font From Google 
import { Inter } from "next/font/google";

// Importing the Global CSS File
import "./globals.css";

// Importing the Navbar Component
import Navbar from "@/components/Navbar";

// Inter Font Variable
const inter = Inter({ subsets: ["latin"] });

// Setting the Meta Data
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// Function to render the html content
export default function RootLayout({
    children, // children are nothing but just react component, that we are getting from 'page.tsx'
}:
    // Defining the Readonly Children's as it is typescript
    Readonly<{
        // Here we are defining the type of the children as it is typescript
        children: React.ReactNode;
    }>) {
    return (
        // Adding the dark class to make the website default in Dark Mode (Will add toggle to Change Theme)
        <html lang="en" className="dark">
            <body className={inter.className}>

                {/* Importing the Navbar Component From the Components Folder */}
                <div className="relative w-full flex items-center justify-center ">
                    <Navbar />
                </div>

                {children}
            </body>
        </html>
    );
}
