// In Next JS, For Every Folder, we have 2 main files and that files should be present
// First One is layout.tsx and Second One is page.tsx
// layout.tsx ==> This File Generally Used to define the layout for the Page
// page.tsx ==> This File Contains the Content that we have to show or display on the web page

// Importing the Metadata for the Web Page
import type { Metadata } from "next";

// Importing the Inter Font From Google 
import { Inter } from "next/font/google";

// Importing the Global CSS File
import "./globals.css";

// Inter Font Variable
const inter = Inter({ subsets: ["latin"] });

// Setting the Meta Data
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// Function to render the html content
export default function RootLayout({
    children, // children are nothing but just react component, that we are getting from 'page.tsx'
}: 
// Defining the Readonly Children's as it is typescript
Readonly<{
    // Here we are defining the type of the children as it is typescript
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                
                {/* Adding the Nav Bar Sample */}
                <h2 className="text-center text-bold">Navigation Bar Will be Here</h2>

                {children}
            </body>
        </html>
    );
}
